services:
  _defaults:
    autowire: true
    autoconfigure: true

  Tourze\RobotsTxtBundle\Controller\:
    resource: '../../Controller/'
  Tourze\RobotsTxtBundle\Provider\:
    resource: '../../Provider/'
  Tourze\RobotsTxtBundle\Service\:
    resource: '../../Service/'
  
  # 为测试明确配置 AttributeControllerLoader 服务
  Tourze\RobotsTxtBundle\Service\AttributeControllerLoader:
    public: true
