<?php

namespace Tourze\RobotsTxtBundle\Tests\Model\RobotsTxtEntry;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\TestCase;
use Tourze\RobotsTxtBundle\Model\RobotsTxtDirective;
use Tourze\RobotsTxtBundle\Model\RobotsTxtEntry;
use Tourze\RobotsTxtBundle\Model\RobotsTxtRule;

/**
 * @internal
 */
#[CoversClass(RobotsTxtEntry::class)]
final class RobotsTxtEntryMergeTest extends TestCase
{
    public function testMergeWithEmptyEntries(): void
    {
        $entry1 = new RobotsTxtEntry();
        $entry2 = new RobotsTxtEntry();
        $merged = $entry1->merge($entry2);

        $this->assertEquals([], $merged->rules);
        $this->assertEquals([], $merged->sitemaps);
        $this->assertEquals([], $merged->comments);
    }

    public function testMergeWithRulesOnly(): void
    {
        $rule1 = RobotsTxtRule::forAllAgents([RobotsTxtDirective::disallow('/admin/')]);
        $rule2 = RobotsTxtRule::forAgent('Googlebot', [RobotsTxtDirective::allow('/api/')]);

        $entry1 = new RobotsTxtEntry([$rule1]);
        $entry2 = new RobotsTxtEntry([$rule2]);
        $merged = $entry1->merge($entry2);

        $this->assertEquals([$rule1, $rule2], $merged->rules);
        $this->assertEquals([], $merged->sitemaps);
        $this->assertEquals([], $merged->comments);
    }

    public function testMergeWithSitemapsOnly(): void
    {
        $sitemap1 = 'https://example.com/sitemap1.xml';
        $sitemap2 = 'https://example.com/sitemap2.xml';

        $entry1 = new RobotsTxtEntry([], [$sitemap1]);
        $entry2 = new RobotsTxtEntry([], [$sitemap2]);
        $merged = $entry1->merge($entry2);

        $this->assertEquals([], $merged->rules);
        $this->assertEquals([$sitemap1, $sitemap2], $merged->sitemaps);
        $this->assertEquals([], $merged->comments);
    }

    public function testMergeWithCommentsOnly(): void
    {
        $comment1 = 'First comment';
        $comment2 = 'Second comment';

        $entry1 = new RobotsTxtEntry([], [], [$comment1]);
        $entry2 = new RobotsTxtEntry([], [], [$comment2]);
        $merged = $entry1->merge($entry2);

        $this->assertEquals([], $merged->rules);
        $this->assertEquals([], $merged->sitemaps);
        $this->assertEquals([$comment1, $comment2], $merged->comments);
    }

    public function testMergeWithAllComponents(): void
    {
        $rule1 = RobotsTxtRule::forAllAgents([RobotsTxtDirective::disallow('/private/')]);
        $rule2 = RobotsTxtRule::forAgent('Bingbot', [RobotsTxtDirective::crawlDelay(5)]);

        $sitemap1 = 'https://example.com/sitemap1.xml';
        $sitemap2 = 'https://example.com/sitemap2.xml';

        $comment1 = 'Generated by system';
        $comment2 = 'Last updated today';

        $entry1 = new RobotsTxtEntry([$rule1], [$sitemap1], [$comment1]);
        $entry2 = new RobotsTxtEntry([$rule2], [$sitemap2], [$comment2]);
        $merged = $entry1->merge($entry2);

        $this->assertEquals([$rule1, $rule2], $merged->rules);
        $this->assertEquals([$sitemap1, $sitemap2], $merged->sitemaps);
        $this->assertEquals([$comment1, $comment2], $merged->comments);
    }

    public function testMergeWithFirstEntryEmpty(): void
    {
        $rule = RobotsTxtRule::forAgent('TestBot', [RobotsTxtDirective::allow('/test/')]);
        $sitemap = 'https://example.com/sitemap.xml';
        $comment = 'Test comment';

        $entry1 = new RobotsTxtEntry();
        $entry2 = new RobotsTxtEntry([$rule], [$sitemap], [$comment]);
        $merged = $entry1->merge($entry2);

        $this->assertEquals([$rule], $merged->rules);
        $this->assertEquals([$sitemap], $merged->sitemaps);
        $this->assertEquals([$comment], $merged->comments);
    }

    public function testMergeWithSecondEntryEmpty(): void
    {
        $rule = RobotsTxtRule::forAgent('TestBot', [RobotsTxtDirective::allow('/test/')]);
        $sitemap = 'https://example.com/sitemap.xml';
        $comment = 'Test comment';

        $entry1 = new RobotsTxtEntry([$rule], [$sitemap], [$comment]);
        $entry2 = new RobotsTxtEntry();
        $merged = $entry1->merge($entry2);

        $this->assertEquals([$rule], $merged->rules);
        $this->assertEquals([$sitemap], $merged->sitemaps);
        $this->assertEquals([$comment], $merged->comments);
    }

    public function testMergeWithDuplicateItems(): void
    {
        $rule = RobotsTxtRule::forAllAgents([RobotsTxtDirective::disallow('/admin/')]);
        $sitemap = 'https://example.com/sitemap.xml';
        $comment = 'Duplicate comment';

        $entry1 = new RobotsTxtEntry([$rule], [$sitemap], [$comment]);
        $entry2 = new RobotsTxtEntry([$rule], [$sitemap], [$comment]);
        $merged = $entry1->merge($entry2);

        // Should preserve duplicates as the merge is a simple concatenation
        $this->assertEquals([$rule, $rule], $merged->rules);
        $this->assertEquals([$sitemap, $sitemap], $merged->sitemaps);
        $this->assertEquals([$comment, $comment], $merged->comments);
    }

    public function testMergePreservesOriginalEntries(): void
    {
        $rule1 = RobotsTxtRule::forAllAgents([RobotsTxtDirective::disallow('/admin/')]);
        $rule2 = RobotsTxtRule::forAgent('Googlebot', [RobotsTxtDirective::allow('/api/')]);

        $entry1 = new RobotsTxtEntry([$rule1]);
        $entry2 = new RobotsTxtEntry([$rule2]);
        $merged = $entry1->merge($entry2);

        // Original entries should remain unchanged
        $this->assertEquals([$rule1], $entry1->rules);
        $this->assertEquals([$rule2], $entry2->rules);

        // Merged entry should have both rules
        $this->assertEquals([$rule1, $rule2], $merged->rules);
    }

    public function testMergeWithMultipleRulesAndComponents(): void
    {
        $rules1 = [
            RobotsTxtRule::forAllAgents([RobotsTxtDirective::disallow('/admin/')]),
            RobotsTxtRule::forAgent('Googlebot', [RobotsTxtDirective::crawlDelay(1)]),
        ];
        $rules2 = [
            RobotsTxtRule::forAgent('Bingbot', [RobotsTxtDirective::allow('/api/')]),
            RobotsTxtRule::forAgent('DuckDuckBot', [RobotsTxtDirective::disallow('/private/')]),
        ];

        $sitemaps1 = ['https://example.com/sitemap1.xml', 'https://example.com/sitemap2.xml'];
        $sitemaps2 = ['https://example.com/sitemap3.xml'];

        $comments1 = ['First entry comment', 'Generated at startup'];
        $comments2 = ['Second entry comment'];

        $entry1 = new RobotsTxtEntry($rules1, $sitemaps1, $comments1);
        $entry2 = new RobotsTxtEntry($rules2, $sitemaps2, $comments2);
        $merged = $entry1->merge($entry2);

        $expectedRules = [...$rules1, ...$rules2];
        $expectedSitemaps = [...$sitemaps1, ...$sitemaps2];
        $expectedComments = [...$comments1, ...$comments2];

        $this->assertEquals($expectedRules, $merged->rules);
        $this->assertEquals($expectedSitemaps, $merged->sitemaps);
        $this->assertEquals($expectedComments, $merged->comments);

        $this->assertCount(4, $merged->rules);
        $this->assertCount(3, $merged->sitemaps);
        $this->assertCount(3, $merged->comments);
    }

    public function testMergeChainedMerging(): void
    {
        $entry1 = new RobotsTxtEntry(
            [RobotsTxtRule::forAllAgents([RobotsTxtDirective::disallow('/admin/')])],
            ['https://example.com/sitemap1.xml'],
            ['Entry 1']
        );

        $entry2 = new RobotsTxtEntry(
            [RobotsTxtRule::forAgent('Googlebot', [RobotsTxtDirective::allow('/api/')])],
            ['https://example.com/sitemap2.xml'],
            ['Entry 2']
        );

        $entry3 = new RobotsTxtEntry(
            [RobotsTxtRule::forAgent('Bingbot', [RobotsTxtDirective::crawlDelay(10)])],
            ['https://example.com/sitemap3.xml'],
            ['Entry 3']
        );

        $mergedFirst = $entry1->merge($entry2);
        $merged = $mergedFirst->merge($entry3);

        $this->assertCount(3, $merged->rules);
        $this->assertCount(3, $merged->sitemaps);
        $this->assertCount(3, $merged->comments);

        $this->assertEquals('Entry 1', $merged->comments[0]);
        $this->assertEquals('Entry 2', $merged->comments[1]);
        $this->assertEquals('Entry 3', $merged->comments[2]);
    }

    public function testToString(): void
    {
        $rule1 = RobotsTxtRule::forAllAgents([RobotsTxtDirective::disallow('/admin/')]);
        $rule2 = RobotsTxtRule::forAgent('Googlebot', [RobotsTxtDirective::crawlDelay(5)]);

        $entry1 = new RobotsTxtEntry([$rule1], ['https://example.com/sitemap1.xml'], ['Comment 1']);
        $entry2 = new RobotsTxtEntry([$rule2], ['https://example.com/sitemap2.xml'], ['Comment 2']);

        $merged = $entry1->merge($entry2);

        $expected = "# Comment 1\n# Comment 2\n\nUser-agent: *\nDisallow: /admin/\n\nUser-agent: Googlebot\nCrawl-delay: 5\n\nSitemap: https://example.com/sitemap1.xml\nSitemap: https://example.com/sitemap2.xml";
        $this->assertEquals($expected, $merged->toString());
    }

    public function testWithComment(): void
    {
        $rule = RobotsTxtRule::forAllAgents([RobotsTxtDirective::disallow('/admin/')]);
        $entry1 = new RobotsTxtEntry([$rule], [], ['Original comment']);
        $entry2 = new RobotsTxtEntry();

        $merged = $entry1->merge($entry2);
        $newEntry = $merged->withComment('New comment');

        $this->assertEquals(['Original comment'], $merged->comments);
        $this->assertEquals(['Original comment', 'New comment'], $newEntry->comments);
    }

    public function testWithRule(): void
    {
        $rule1 = RobotsTxtRule::forAllAgents([RobotsTxtDirective::disallow('/admin/')]);
        $rule2 = RobotsTxtRule::forAgent('Googlebot', [RobotsTxtDirective::crawlDelay(5)]);

        $entry1 = new RobotsTxtEntry([$rule1]);
        $entry2 = new RobotsTxtEntry();

        $merged = $entry1->merge($entry2);
        $newEntry = $merged->withRule($rule2);

        $this->assertEquals([$rule1], $merged->rules);
        $this->assertEquals([$rule1, $rule2], $newEntry->rules);
    }

    public function testWithRules(): void
    {
        $rule1 = RobotsTxtRule::forAllAgents([RobotsTxtDirective::disallow('/admin/')]);
        $newRules = [
            RobotsTxtRule::forAgent('Googlebot', [RobotsTxtDirective::crawlDelay(5)]),
            RobotsTxtRule::forAgent('Bingbot', [RobotsTxtDirective::allow('/api/')]),
        ];

        $entry1 = new RobotsTxtEntry([$rule1]);
        $entry2 = new RobotsTxtEntry();

        $merged = $entry1->merge($entry2);
        $newEntry = $merged->withRules($newRules);

        $this->assertEquals([$rule1], $merged->rules);
        $this->assertEquals([$rule1, ...$newRules], $newEntry->rules);
    }

    public function testWithSitemap(): void
    {
        $entry1 = new RobotsTxtEntry([], ['https://example.com/sitemap1.xml']);
        $entry2 = new RobotsTxtEntry();

        $merged = $entry1->merge($entry2);
        $newEntry = $merged->withSitemap('https://example.com/sitemap2.xml');

        $this->assertEquals(['https://example.com/sitemap1.xml'], $merged->sitemaps);
        $this->assertEquals(['https://example.com/sitemap1.xml', 'https://example.com/sitemap2.xml'], $newEntry->sitemaps);
    }

    public function testWithSitemaps(): void
    {
        $entry1 = new RobotsTxtEntry([], ['https://example.com/sitemap1.xml']);
        $entry2 = new RobotsTxtEntry();

        $newSitemaps = [
            'https://example.com/sitemap2.xml',
            'https://example.com/sitemap3.xml',
        ];

        $merged = $entry1->merge($entry2);
        $newEntry = $merged->withSitemaps($newSitemaps);

        $this->assertEquals(['https://example.com/sitemap1.xml'], $merged->sitemaps);
        $this->assertEquals(['https://example.com/sitemap1.xml', ...$newSitemaps], $newEntry->sitemaps);
    }
}
