<?php

namespace Tourze\RobotsTxtBundle\Provider;

use Tourze\RobotsTxtBundle\Model\RobotsTxtDirective;
use Tourze\RobotsTxtBundle\Model\RobotsTxtEntry;
use Tourze\RobotsTxtBundle\Model\RobotsTxtRule;

/**
 * 默认的robots.txt提供者
 *
 * 提供基本的默认规则
 */
class DefaultRobotsTxtProvider implements RobotsTxtProviderInterface
{
    public function provide(): RobotsTxtEntry
    {
        $entry = new RobotsTxtEntry();

        // 添加默认注释
        $entry = $entry->withComment('Generated by RobotsTxtBundle');

        // 添加基本规则：允许所有爬虫访问所有内容
        $rule = RobotsTxtRule::forAllAgents([
            RobotsTxtDirective::disallow(''), // 空字符串表示允许所有路径
        ]);

        return $entry->withRule($rule);
    }

    public function getPriority(): int
    {
        return -1000; // 最低优先级，作为默认值
    }

    public function supports(): bool
    {
        return true; // 总是支持
    }
}
